### ISSUE TITLE
Security Alerts report

### ISSUE THREAD

**Issue by webdog** [ghapplets/ghapplets.github.io#1]
@pierluigi @leefaus What's the best way to remediate these security alerts:

![image](https://user-images.githubusercontent.com/960210/47758099-8bd4d400-dc77-11e8-92c5-53dfb18c1e53.png)

The documents suggest to update the dependencies to specific versions, but I only see the alerts listed in the package-lock, not the package.json file. I'm not a JS person, so unsure what's the best practice here.

😺

**Comment by pierluigi** [comment]
I have updated all packages to the latest possible versions (`*`) and the `-lock.json` file correspondingly. It seems like some packages we depend on are importing those vulns. 
Given this only affects our `devDependencies`, there are 0 client-side js dependencies, and that the final build has to be produced locally I see no real threat here.
